# Generated by Django 3.0.7 on 2020-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200626_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='fields',
            field=models.ManyToManyField(to='core.Field'),
        ),
    ]
