# Generated by Django 3.0.7 on 2020-06-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='using',
            field=models.ManyToManyField(related_name='used_by', to='core.Source'),
        ),
    ]
