# Generated by Django 3.0.7 on 2020-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_using'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='author_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='fields',
            field=models.ManyToManyField(blank=True, to='core.Field'),
        ),
        migrations.AlterField(
            model_name='source',
            name='using',
            field=models.ManyToManyField(blank=True, related_name='used_by', to='core.Source'),
        ),
    ]
